name: Build and Upload Executables

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
      - 'snapshot-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: make test

      - name: Build project
        run: make build-all

      - name: List bin directory contents
        run: ls -la bin/

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: bin/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: bin/*
